### ISSUE TITLE
Function naming conventions

### ISSUE THREAD

**Issue by lsrdg** [kriadmin/30-seconds-of-python-code#1] opened 2018-01-09 09:41 UTC
**Category:** naming conventions

### Summary:
[CONTRIBUTING](https://github.com/kriadmin/30-seconds-of-python-code/blob/master/CONTRIBUTING.md) links to PEP8 [which suggests](https://www.python.org/dev/peps/pep-0008/#function-names):

> 
> Function names should be lowercase, with words separated by underscores as necessary to improve readability.
> 
> mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.

`countOccurences()` and `countVowels()` are camel-cased.

### Possible Solution

Just let me know if you want a PR. 30-seconds-of-python-code sounds like a nice idea and I would contribute to (hopefully with more meaningful contributions) than this.

**Comment by kriadmin** [comment] 2018-01-09 12:19
Wait that is an error in the contributing.md

**Comment by lsrdg** [comment] 2018-01-09 12:40
If it is just that I can do it right now, but are you sure? I thought the PR would be the other way around: rename the functions, so that all functions follow the same style.

**Comment by kriadmin** [comment] 2018-01-09 12:44
No actually first I thought of following the PEP8 guidelines but then I met [yapf](https://github.com/google/yapf). So I updated it but forgot to remove the PEP8 part. If you are busy I shall do it.

**Comment by lsrdg** [comment] 2018-01-09 12:55
I think you should it, even better if you clarify why the project is taking this specific direction. Since it is a python project, I would rather follow pep8, flake8, pylint etc and not what google has to say about that, but totally respect your decision. (=

**Comment by kriadmin** [comment] 2018-01-10 18:20
Yeah I think you right about following the right style conventions. I think
I was stupid to use javascript naming conventions in python. I will reopen
to issue to discuss the styles to be used.  :)

**Comment by lsrdg** [comment] 2018-01-10 21:13
In python, I guess "we are all adults"... but maybe it helps if you define the target(s) user(s) group(s)? 

If most users are coming here after knowing the javascript version, the js naming style would be one less thing to worry about and people would focus on the code itself.

Experienced programmers just getting started with python will use their own filters to decide what to use or not.

However, people just starting their path (python as a first language) might need a reinforcement of good code style. Intermediates who are constancy reading the docs won't have a problem with that, but it might be a mental relief to know what type an object is just by staring at it.

You can also just set up a linter of your choice on travis and tell people that their PR will be merged when all tests are passing. 

What are _your_ thoughts on the topic?

**Comment by kriadmin** [comment] 2018-01-11 05:51
The target users are both beginners who have just started learning python to experts (`adults`) who use it daily. We will be helping the beginners as each of our code is accompanied with  a short and clear description about the _**inbuilt**_  python function and modules we use. We will help the everyday users by providing copy-paste snippets that might need to use on a regular basis. (Although it is not the main focus but we might provide a library/module with all the snippets).

No we are not going to get any traffic from the Javascript version as this project is not mentioned anywhere in their project.

Yeah I think you are right about reinforcing good code style and I think I have included a checkbox if the code style of this project is used by there code in the PR-template. I believe there are many code-styles which have little differences. We should use the most used one so that most of the advanced users are comfortable with it.

Yeah I think you are right about mention somewhere that there PR will be merged when tests pass. I think we can even ensure that there examples are working as intended. We can set up a linter when we have decided the code-style to be used. Also do you know any code prettifiers for python I couldn't find anything else than `yapf`

**Comment by lsrdg** [comment] 2018-01-12 11:45
It sounds like a really python centric/minded/focused project, so no reason to use other language's styles.

>We can set up a linter when we have decided the code-style to be used. Also do you know any code prettifiers for python I couldn't find anything else than yapf

If the linter detects any error the pass will fail and won't be merged until a new commit (added to the PR) fix that. I fail to see why to automatically prettify the code... :/

Tools to take a look at:
- [flake8](https://github.com/PyCQA/flake8)
- [pylint](https://github.com/PyCQA/pylint)
- [autopep8](https://github.com/hhatto/autopep8)

**Comment by kriadmin** [comment] 2018-01-12 16:34
I went through all them and came to the conclusion that they check your code for errors .
I also searched for them on Google and read that pylint has many unnecessary errors and warnings. 

But I really liked autopep8 and I think it prettifies your code too. 

So I think we have made a decision but I wanted your opinions on it. 

Also would like to submit a PR to integrate autopep8. I might be able to do you it after reading the documentation but as you are more experienced you will do it better.

**Comment by Rob-Rychs** [comment] 2018-01-12 19:11
Hey guys I just found [this](https://github.com/PyCQA/pycodestyle) looks pretty good for pep8 too...

**Comment by lsrdg** [comment] 2018-01-12 20:58
I've used flake8 and autopep8 in a project, but when I tried pylint (locally) it did point to so many stuff that I learned a lot. I'm using flake8 on travis and pylint locally for my own sake... whichever tool you choose will give a decent code style, but again I fail to see why the code should be automatically prettified. (: 

> but as you are more experienced you will do it better.

Nope. Just a learner as well. It is nice to open the space for discussion, but as the maintainer it is up to you @kriadmin to take a decision. We always assign an issue to ourselves or open an issue to discuss whatever is relevant. (:

@Rob-Rychs , well pointed. That's what I liked about flake8:

    Flake8 is a wrapper around these tools:

    - PyFlakes
    - pycodestyle
    - Ned Batchelder's McCabe script

**Comment by kriadmin** [comment] 2018-01-13 06:49
@lsrdg I want to auto-prettify code because some people really like to write babdly formatted code(I am an example).

@Rob-Rychs I will check that out in the evening today(I am +5:30) and will be busy today. And after checking it out I will decide on one(hopefully)  and then integrate it for travis-ci

**Comment by lsrdg** [comment] 2018-01-13 09:21
@kriadmin aha, no problems. Probably I'm just on the side of the people who really enjoy using a text editor :P 

In this case, you can create another branch to test the linter+prettifier and we can keep the discussion on the PR, what do you think?

**Comment by kriadmin** [comment] 2018-01-13 14:35
Yes I was thinking of making a branch to test it but I am really busy because I have exams coming. Still I will try my best to make a PR soon.

**Closed** 2018-01-16 12:31 UTC
Labels: good first issue, opinions needed
